version: "2"
services:
  tmpnginx:
    image: nginx
    restart: always
    ports:
      - "18030:80"
    networks:
      - tmpnetwork

  tmpmysql:
    image: mysql
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - tmpnetwork

networks:
  tmpnetwork:
    driver: bridge