version: "3"
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - default

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - default

  gogs:
    image: gogs/gogs
    container_name: gogs
    restart: always
    depends_on:
      - mysql
      - nginx
    networks:
      - default
    ports:
      - "10022:22"
      - "10080:3000"

  redis:
    image: redis
    container_name: redis
    restart: always
    networks:
      - default
    ports:
      - "6379:6379"
