version: "3"
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    networks:
      - default
    ports:
      - "80:80"
    volumes:
      - /mnt/nginx/html:/usr/share/nginx/html
      - /mnt/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /mnt/nginx/conf.d:/etc/nginx/conf.d

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    networks:
      - default
    ports:
      - "13306:3306"
    volumes:
      - /mnt/mysql/my.cnf:/etc/mysql/my.cnf:ro
      - /mnt/mysql/data:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456

  gogs:
    image: gogs/gogs
    container_name: gogs
    restart: always
    depends_on:
      - mysql
      - nginx
    networks:
      - default
    ports:
      - "10022:22"
      - "10080:3000"
    volumes:
      - /mnt/gogs:/data

  redis:
    image: redis
    container_name: redis
    restart: always
    networks:
      - default
    ports:
      - "6379:6379"
