version: "3.8"
services:
  frps:
    build:
      context: ./frp/frps/${FRPS_ARCH}
      args:
        - FRP_VERSION=${FRP_VERSION}
        - ZP_MAINTAINER=${ZP_MAINTAINER}
    container_name: frps
    privileged: true
    restart: always
    volumes:
      - ${FRPS_INI_PATH}:/etc/frp/frps.ini
    networks:
      backend:
        ipv4_address: ${FRPS_IP}

  frpc:
    build:
      context: ./frp/frpc/${FRPC_ARCH}
      args:
        - FRP_VERSION=${FRP_VERSION}
        - ZP_MAINTAINER=${ZP_MAINTAINER}
    container_name: frpc
    privileged: true
    restart: always
    volumes:
      - ${FRPC_INI_PATH}:/etc/frp/frpc.ini
    networks:
      backend:
        ipv4_address: ${FRPC_IP}

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}
