version: "2"
services:

  ######## nginx ########
  nginx:
    build:
      context: ./nginx
      args:
        - ZP_MAINTAINER=${ZP_MAINTAINER}
    image: ${AUTHOR}/${NGINX_NAME}:${TAG}
    container_name: ${NGINX_NAME}
    restart: always
    privileged: true
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
      - ${NGINX_HOST_HTTPS_PORT}:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ${NGINX_ROOT_PATH}:/var/www/
      - ${NGINX_LOG_PATH}:/var/log/nginx/
    networks:
      backend:
        ipv4_address: ${NGINX_IP}

  ######## redis ########
  redis:
    build:
      context: ./redis
      args:
        - VERSION=${REDIS_VERSION}
        - ZP_MAINTAINER=${ZP_MAINTAINER}
    image: ${AUTHOR}/${REDIS_NAME}:${TAG}
    container_name: ${REDIS_NAME}
    restart: always
    privileged: true
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ${REDIS_DATA_PATH}:/data
      - ${REDIS_CONF_PATH}:/etc/redis/redis.conf
    networks:
      backend:
        ipv4_address: ${REDIS_IP}

  ######## mysql ########
  mysql:
    build:
      context: ./mysql
      args:
        - VERSION=${MYSQL_VERSION}
        - ZP_MAINTAINER=${ZP_MAINTAINER}
    image: ${AUTHOR}/${MYSQL_NAME}:${TAG}
    container_name: ${MYSQL_NAME}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${MYSQL_TIMEZONE}
    volumes:
      - ${MYSQL_CONF_PATH}:/etc/mysql/conf.d/docker.cnf:ro
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
    # M1 需要指定 platform
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    privileged: true
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      backend:
        ipv4_address: ${MYSQL_IP}

  ######## frps ########
  frps:
    build:
      context: ./frp/frps/${FRPS_ARCH}
      args:
        - FRP_VERSION=${FRP_VERSION}
        - ZP_MAINTAINER=${ZP_MAINTAINER}
    image: ${AUTHOR}/${FRPS_NAME}:${TAG}
    container_name: ${FRPS_NAME}
    restart: always
    privileged: true
    ports:
      # frps服务端口
      - '6500:7000'
      # web管理端口
      - '6501:7500'
      - '6502:7001'
      # http端口
      - '6503:80'
      # https端口
      - '6504:443'
      # 开放给frpc的端口
      - '3505-3510:3505-3510'
    volumes:
      - ${FRPS_INI_PATH}:/etc/frp/frps.toml
      - ${FRPS_LOG_PATH}:/var/log/frps.log
    networks:
      backend:
        ipv4_address: ${FRPS_IP}

  ######## frpc ########
  frpc:
    build:
      context: ./frp/frpc/${FRPC_ARCH}
      args:
        - FRP_VERSION=${FRP_VERSION}
        - ZP_MAINTAINER=${ZP_MAINTAINER}
    image: ${AUTHOR}/${FRPC_NAME}:${TAG}
    container_name: ${FRPC_NAME}
    restart: always
    privileged: true
    volumes:
      - ${FRPC_INI_PATH}:/etc/frp/frpc.toml
      - ${FRPC_LOG_PATH}:/var/log/frpc.log
    networks:
      backend:
        ipv4_address: ${FRPC_IP}

  ######## wordpress ########
  wp:
    image: wordpress:latest
    container_name: wp
    restart: always
    privileged: true
    ports:
      - ${WP_PORT}:80
    volumes:
      - ${WP_CONF_PATH}:/usr/local/etc/php/conf.d/conf.ini
      - ${WP_ROOT_PATH}:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: "${WP_DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${WP_DB_ROOT_PASSWORD}"
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      backend:
        ipv4_address: ${WP_IP}

  ###### wordpress-cli ######
  wpcli:
    image: wordpress:cli
    container_name: wpcli
    restart: always
    privileged: true
    volumes:
      - ${WP_CONF_PATH}:/usr/local/etc/php/conf.d/conf.ini
      - ${WP_ROOT_PATH}:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: "${WP_DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${WP_DB_ROOT_PASSWORD}"
    depends_on:
      - mysql
      - wp
    networks:
      backend:
        ipv4_address: ${WP_CLI_IP}

  ######## goapp110 ########
  goapp110:
    build:
      context: ./golang
      args:
        - VERSION=${GO_VERSION}
        - ZP_MAINTAINER=${ZP_MAINTAINER}
    image: ${AUTHOR}/${GOAPP110_NAME}:${TAG}
    container_name: ${GOAPP110_NAME}
    restart: always
    privileged: true
    ports:
      - '8000:80'
    volumes:
      - ${GO_APPPATH}:/var/www/goapp/
    environment:
      - TZ=${GO_TIMEZONE}
    networks:
      backend:
        ipv4_address: ${GOAPP_IP10}

  ######## goapp111 ########
  goapp111:
    build:
      context: ./golang
      args:
        - VERSION=${GO_VERSION}
        - ZP_MAINTAINER=${ZP_MAINTAINER}
    image: ${AUTHOR}/${GOAPP111_NAME}:${TAG}
    container_name: ${GOAPP111_NAME}
    restart: always
    privileged: true
    ports:
      - '8000:80'
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - ${GO_APPPATH}:/var/www/goapp/
    environment:
      - TZ=${GO_TIMEZONE}
    networks:
      backend:
        ipv4_address: ${GOAPP_IP11}

  ######## goapp112 ########
  goapp112:
    build:
      context: ./golang
      args:
        - VERSION=${GO_VERSION}
        - ZP_MAINTAINER=${ZP_MAINTAINER}
    image: ${AUTHOR}/${GOAPP112_NAME}:${TAG}
    container_name: ${GOAPP112_NAME}
    restart: always
    privileged: true
    ports:
      - '8000:80'
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - ${GO_APPPATH}:/var/www/goapp/
    environment:
      - TZ=${GO_TIMEZONE}
    networks:
      backend:
        ipv4_address: ${GOAPP_IP12}

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}

