# frpc.ini

# 假设 frps 所在的服务器的 IP 为 <0.0.0.0>，local_port 为本地机器上 Web 服务监听的端口, 绑定自定义域名为 custom_domains。
[common]
server_addr = <0.0.0.0>
server_port = 7000

[web01]
type = http
local_port = 80
custom_domains = <www.example2.com>

[web02]
type = http
local_port = 8080
custom_domains = <www.example2.com>
