version: "3"

networks:
  Vpc:
    external:
      name: Vpc01

services:
  gitea-app:
    image: gitea/gitea
    container_name: gitea-app
    restart: unless-stopped
    volumes:
      - ./app:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=gitea-db:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    depends_on:
      - gitea-db
    networks:
      - Vpc

  gitea-db:
    image: mysql
    container_name: gitea-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
    networks:
      - Vpc
    volumes:
      - ./data:/var/lib/mysql
