version: "3"

networks:
  Vpc:
    external:
      name: Vpc01

services:
  proxy:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    ports:
      - 80:80
      - 443:443
    networks:
      - Vpc
