name: frps-i386
on:
  push:
    # branches:
    #   - master
    tags:
      - 'v*.*.*'
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: frp/frps/i386
          platforms: linux/386
          build-args: |
              FRP_VERSION=${{ secrets.FRP_VERSION }}
              ZP_MAINTAINER=${{ secrets.ZP_MAINTAINER }}
          push: false
